USE Sai;
CREATE TABLE LIC (LIC_ID INT PRIMARY KEY, 
					  DURATION VARCHAR(50),
					  POLICY_ID VARCHAR(50),
					  POLICY_NAME VARCHAR(50))

					  

CREATE TABLE POLICYHOLDER (POLICY_ID INT PRIMARY KEY,
						PNAME VARCHAR(50),
					    LIC_ID INT FOREIGN KEY REFERENCES LIC(LIC_ID));
,
				