//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.23 at 05:41:53 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.bhavna.com/student", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_bhavna_com.student;
